// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

package service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetUsernameReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsernameReq) Reset()         { *m = GetUsernameReq{} }
func (m *GetUsernameReq) String() string { return proto.CompactTextString(m) }
func (*GetUsernameReq) ProtoMessage()    {}
func (*GetUsernameReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{0}
}

func (m *GetUsernameReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsernameReq.Unmarshal(m, b)
}
func (m *GetUsernameReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsernameReq.Marshal(b, m, deterministic)
}
func (m *GetUsernameReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsernameReq.Merge(m, src)
}
func (m *GetUsernameReq) XXX_Size() int {
	return xxx_messageInfo_GetUsernameReq.Size(m)
}
func (m *GetUsernameReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsernameReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsernameReq proto.InternalMessageInfo

type GetUsernameRes struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsernameRes) Reset()         { *m = GetUsernameRes{} }
func (m *GetUsernameRes) String() string { return proto.CompactTextString(m) }
func (*GetUsernameRes) ProtoMessage()    {}
func (*GetUsernameRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{1}
}

func (m *GetUsernameRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsernameRes.Unmarshal(m, b)
}
func (m *GetUsernameRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsernameRes.Marshal(b, m, deterministic)
}
func (m *GetUsernameRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsernameRes.Merge(m, src)
}
func (m *GetUsernameRes) XXX_Size() int {
	return xxx_messageInfo_GetUsernameRes.Size(m)
}
func (m *GetUsernameRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsernameRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsernameRes proto.InternalMessageInfo

func (m *GetUsernameRes) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*GetUsernameReq)(nil), "service.GetUsernameReq")
	proto.RegisterType((*GetUsernameRes)(nil), "service.GetUsernameRes")
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor_ca53982754088a9d) }

var fileDescriptor_ca53982754088a9d = []byte{
	// 119 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0xcd, 0xcd,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x55,
	0x12, 0xe0, 0xe2, 0x73, 0x4f, 0x2d, 0x09, 0x2d, 0x4e, 0x2d, 0xca, 0x4b, 0xcc, 0x4d, 0x0d, 0x4a,
	0x2d, 0x54, 0xd2, 0x41, 0x13, 0x29, 0x16, 0x92, 0xe2, 0xe2, 0x28, 0x85, 0x72, 0x25, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0xe0, 0x7c, 0x23, 0x3f, 0x2e, 0x6e, 0x97, 0xd4, 0xdc, 0xfc, 0x60, 0x88,
	0x71, 0x42, 0xf6, 0x5c, 0xdc, 0x48, 0x9a, 0x85, 0xc4, 0xf5, 0xa0, 0xf6, 0xe8, 0xa1, 0x5a, 0x22,
	0x85, 0x43, 0xa2, 0x38, 0x89, 0x0d, 0xec, 0x3e, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x15,
	0xbc, 0x0c, 0x19, 0xad, 0x00, 0x00, 0x00,
}
